### ISSUE TITLE
QueryParam and PathParams use primatives

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/lib-gradle-container-utils#18]
In our old tools, generated resource interfaces used boxed primitives as method parameters (with QueryParam and PathParam annotations).  This enabled these to be optional and null in the implementing classes (would never(?) be on PathParams but optional QueryParams without defaults could easily be written into the RAML.  Box these primitive args.

**Comment by Foxcapades** [comment]
Fixed by v4.8.3
